version: '3'

services:
  api:
    container_name: wongames_api
    image: gabrielguedess/wongames-api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'sk_test_51LSSFZDeL0VYqb6Sw6pXo8ccudESdcJJUK6WW3hdbzmCR2YgASRW8ZBdrk1MA5S2569oG0WbJLUDfIn9uQ1z3CnD00NMMLKBax'
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: gabrielguedess/wongames-db:latest
    ports:
      - '5432:5432'
